---
title: "selachii-fossil-occurences"
author: "Kelsey Jiang"
output: html_document
---

```{r}
library(ggplot2)

setwd("~/Desktop/eeb-177/EEB-177-Final-Project/Selachii-Data")
sharks <- read.csv("~/Desktop/eeb-177/EEB-177-Final-Project/Selachii-Data/selachii_ranges.csv", header = F, as.is = T)
names(sharks) <- c("genus", "species", "minage", "maxage")
head(sharks)

```

```{r}
sharks_occ <- ggplot(sharks, aes( species, ymin = maxage, ymax = minage, colour = genus))
sharks_occ <- sharks_occ + geom_linerange()
sharks_occ <- sharks_occ + theme(legend.position = "none")
sharks_occ <- sharks_occ + coord_flip()
sharks_occ <- sharks_occ + theme(axis.text.y = element_text(size = 0.9))
sharks_occ <- sharks_occ + theme(axis.ticks.y = element_blank())
sharks_occ <- sharks_occ + scale_y_continuous(limits=c(0, 60), expand = c(0,0), breaks=c(0, 10, 20, 30, 40, 50, 60))
sharks_occ <- sharks_occ + labs(title = "Selachii Fossil Occurrences", x = "Species", y = "Ma Ago") + theme(plot.title = element_text(hjust = 0.5, size = 22, face = "bold"), axis.title=element_text(size=20))
sharks_occ

ggsave(filename = "selachii-occ.pdf", plot = sharks_occ)

```

```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(forcats)

setwd("~/Desktop/eeb-177/EEB-177-Final-Project/Selachii-Data")
sharks1 <- read.csv("~/Desktop/eeb-177/EEB-177-Final-Project/Selachii-Data/selachii_species_part_1.csv", header = F, as.is = T)
names(sharks1) <- c("genus", "species", "minage", "maxage")
head(sharks1)

#sharks1_occ <- ggplot(sharks1, aes( x = species, maxage, colour = genus))
# everything
#sharks1_occ + geom_linerange(aes(ymin = minage, ymax = maxage + 0.5)) + theme(legend.position="none") +  coord_flip() +  theme(axis.text.y = element_text(size=1)) + scale_y_continuous(limits=c(0, 60), expand = c(0, 0), breaks=c(0, 10, 20, 30, 40, 50, 60)) + labs(title = "Selachii Part 1 Fossil Occurrences", x = "Species", y = "Ma ago") + theme(plot.title = element_text(hjust = 0.5, size=22, face = "bold"), axis.title =element_text(size=20)) 

sharks1_occ <- ggplot(sharks1, aes( x = fct_reorder(species, minage, .desc = T), maxage, colour = genus))

sharks1_occ + geom_linerange(aes(ymin = minage, ymax = maxage + 0.5)) + theme(legend.position="none") +  coord_flip() +  theme(axis.text.y = element_text(size=1)) + scale_y_continuous(limits=c(0, 200), expand = c(0, 0), breaks=c(0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200)) + labs(title = "Selachii Part 1 Fossil Occurrences", x = "Species", y = "Ma ago") + theme(plot.title = element_text(hjust = 0.5, size=22, face = "bold"), axis.title =element_text(size=20))

#sharks1_occ + geom_linerange(aes(ymin = minage, ymax = maxage + 0.5)) + theme(legend.position="none") +  coord_flip() +  theme(axis.text.y = element_text(size=1)) + scale_y_continuous(limits=c(0, 200), expand = c(0, 0), breaks=c(0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200)) + labs(title = "Selachii Part 1 Genus Separated Fossil Occurrences", x = "Species", y = "Ma ago") + theme(plot.title = element_text(hjust = 0.5, size=22, face = "bold"), axis.title =element_text(size=20)) + facet_wrap(~ genus, scales = "free")

diversity <- sharks1 %>% gather(key = type, value = age, minage, maxage) %>% mutate(count = ifelse(type == "maxage", 1, -1)) %>% group_by(age) %>% summarise(count = sum(count))  %>% arrange(-age, -count) %>% mutate(diversity = cumsum(count)) 

ggplot(diversity, aes(x = age, y = diversity)) + geom_step()

#ggsave(filename = "selachii-occ-part-1.pdf")
```

```{r}
library(ggplot2)
library(forcats)

setwd("~/Desktop/eeb-177/EEB-177-Final-Project/Selachii-Data")
sharks2 <- read.csv("~/Desktop/eeb-177/EEB-177-Final-Project/Selachii-Data/selachii_species_part_2.csv", header = F, as.is = T)
names(sharks2) <- c("genus", "species", "minage", "maxage")
head(sharks2)

#sharks2_occ <- ggplot(sharks2, aes( x = species, maxage, colour = genus))
# everything
#sharks2_occ + geom_linerange(aes(ymin = minage, ymax = maxage + 0.5)) + theme(legend.position="none") +  coord_flip() +  theme(axis.text.y = element_text(size=1)) + scale_y_continuous(limits=c(0, 60), expand = c(0, 0), breaks=c(0, 10, 20, 30, 40, 50, 60)) + labs(title = "Selachii Part 2 Fossil Occurrences", x = "Species", y = "Ma ago") + theme(plot.title = element_text(hjust = 0.5, size=22, face = "bold"), axis.title =element_text(size=20)) 

sharks2_occ <- ggplot(sharks2, aes( x = fct_reorder(species, minage, .desc = T), maxage, colour = genus))

sharks2_occ + geom_linerange(aes(ymin = minage, ymax = maxage + 0.5)) + theme(legend.position="none") +  coord_flip() +  theme(axis.text.y = element_text(size=1)) + scale_y_continuous(limits=c(0, 200), expand = c(0, 0), breaks=c(0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200)) + labs(title = "Selachii Part 2 Fossil Occurrences", x = "Species", y = "Ma ago") + theme(plot.title = element_text(hjust = 0.5, size=22, face = "bold"), axis.title =element_text(size=20)) 

diversity <- sharks2 %>% gather(key = type, value = age, minage, maxage) %>% mutate(count = ifelse(type == "maxage", 1, -1)) %>% group_by(age) %>% summarise(count = sum(count))  %>% arrange(-age, -count) %>% mutate(diversity = cumsum(count)) 

ggplot(diversity, aes(x = age, y = diversity)) + geom_step()

#ggsave(filename = "selachii-occ-part-2.pdf")

```

```{r}
library(forcats)

sharks_occ <- ggplot(sharks, aes( x = fct_reorder(species, minage, .desc = T), maxage, colour = genus))

sharks_occ + geom_linerange(aes(ymin = minage, ymax = maxage + 0.5)) + theme(legend.position="none") +  coord_flip() +  theme(axis.text.y = element_text(size=1)) + scale_y_continuous(limits=c(0, 50), expand = c(0, 0), breaks=c(0, 10, 20, 30, 40, 50)) + labs(title = "Selachii Fossil Occurrences", x = "Species", y = "Ma ago") + theme(plot.title = element_text(hjust = 0.5, size=22, face = "bold"), axis.title =element_text(size=20)) 
```

```{r}

library(ggmap)
library(maps)
library(mapdata)
world <- map_data("world")
selachii_distribution <- read.csv("/home/eeb177-student/Desktop/eeb-177/EEB-177-Final-Project/Selachii-Data/selachii-coordinates-3.csv", header = F,stringsAsFactors = FALSE)
names(selachii_distribution) <- c("longitude", "latitude")
selachii_distribution$longitude<-as.numeric(selachii_distribution$longitude)
ggplot() + geom_polygon(data = world, aes(x=long, y=lat, group = group)) + geom_point(data=selachii_distribution, aes(x=longitude, y=latitude), color="blue")+ labs(title = "Selachii Fossil Occurrences on World Map")

```

```{r}

library(ggmap)
library(maps)
library(mapdata)
world <- map_data("world")
redlist_distribution <- read.csv("/home/eeb177-student/Desktop/eeb-177/EEB-177-Final-Project/Selachii-Data/reformatted-redlist-data.csv", header = F)
names(redlist_distribution) <- c("longitude", "latitude")
redlist_distribution$longitude<-as.numeric(redlist_distribution$longitude)
ggplot() + geom_polygon(data = world, aes(x=long, y=lat, group = group)) + geom_point(data=redlist_distribution, aes(x=longitude, y=latitude), color="red") + labs(title = "Threatened Selachii Species on World Map - Includes VU, EN, & CR")

library(ggmap)
library(maps)
library(mapdata)
world <- map_data("world")
vulnerable_species <- read.csv("/home/eeb177-student/Desktop/eeb-177/EEB-177-Final-Project/Selachii-Data/reformatted-vulnerable-data.csv", header = F,stringsAsFactors = FALSE)
names(vulnerable_species) <- c("longitude", "latitude")
vulnerable_species$longitude<-as.numeric(vulnerable_species$longitude)
ggplot() + geom_polygon(data = world, aes(x=long, y=lat, group = group)) + geom_point(data=vulnerable_species, aes(x=longitude, y=latitude), color="pink") + labs(title = "Vulnerable Selachii Species on World Map")

library(ggmap)
library(maps)
library(mapdata)
world <- map_data("world")
endangered_species <- read.csv("/home/eeb177-student/Desktop/eeb-177/EEB-177-Final-Project/Selachii-Data/reformatted-endangered-data.csv", header = F,stringsAsFactors = FALSE)
names(endangered_species) <- c("longitude", "latitude")
endangered_species$longitude<-as.numeric(endangered_species$longitude)
ggplot() + geom_polygon(data = world, aes(x=long, y=lat, group = group)) + geom_point(data=endangered_species, aes(x=longitude, y=latitude), color="maroon")+ labs(title = "Endangered Selachii Species on World Map")

library(ggmap)
library(maps)
library(mapdata)
world <- map_data("world")
criticallyendangered_species <- read.csv("/home/eeb177-student/Desktop/eeb-177/EEB-177-Final-Project/Selachii-Data/reformatted-critically-endangered-data.csv", header = F,stringsAsFactors = FALSE)
names(criticallyendangered_species) <- c("longitude", "latitude")
criticallyendangered_species$longitude<-as.numeric(criticallyendangered_species$longitude)
ggplot() + geom_polygon(data = world, aes(x=long, y=lat, group = group)) + geom_point(data=criticallyendangered_species, aes(x=longitude, y=latitude), color="purple")+ labs(title = "Critically Endangered Selachii Species on World Map")


```
